#!/bin/bash

base_path=${PUS_PATH};

# variables for git
git_user=${LDAP_SELFSERVICE_USER%@FIXME.com};
git_password=${LDAP_SELFSERVICE_PASSWORD};
git_working_dir=${base_path}/hiera-autogenerated
git_remote_repo=gitlab.FIXME.com/FIXME/hiera-autogenerated.git
git_branch=${TARGET_BRANCH}

# direcotry in which the yaml files are located
yaml_file_dir=${git_working_dir}/ldap

cd $base_path;

# try to get lock, exit after 20 seconds
printf "\n\n\nPassword Cleanup started, trying to get the lock...\n";
( flock -x -w 20 200 || exit 1
  # Clone repo if it has not been cloned yes (first time)
  if [ ! -d "${git_working_dir}/.git" ]; then
    printf "Git-Repo not created yet, cloning...\n"
    git clone --branch $git_branch https://$git_user:$git_password@$git_remote_repo

    # set config for push!
    cd $git_working_dir
    git config user.name "${git_user}"
    git config user.email "${git_user}@FIXME.com"
    git config push.default matching
  else
    # repo already exists, fetch and reset it
    printf "Git-Repo already created, updating...\n"

    cd $git_working_dir
    git checkout -B $git_branch
    git fetch --all
    git reset --hard origin/$git_branch
  fi

  # switch to target branch
  cd $git_working_dir
  git checkout -B $git_branch

  # cleanup passwords.yaml file with perl script
  cd $base_path
  perl passwordCleanupCronYaml.pl ${yaml_file_dir}/passwords.yaml ${yaml_file_dir}/complete.yaml

  # add and commit changed files
  cd $git_working_dir
  git add .
  git commit -m "Cleanup password.yaml"
  git push origin $git_branch

  # change owner of all files to www-data -> so that apache can change the files too (when a users changes it's password)
  if [ "$(whoami)" == "root" ]; then
    printf "set www-data as owner of all files...\n";
    cd $base_path;
    find ! -name ".htaccess" ! -name ".htpasswd" -exec chown www-data:www-data {} \;
  fi

  printf "Password cleanup finished\n";
) 200>file.lock || printf "did not get lock within 20 seconds\n"
